experiment:
  name: autodl_lora_4090_bs16_gc
  seed: 42

training:
  num_train_epochs: 2
  max_steps: null
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  logging_steps: 20
  eval_steps: 1000
  save_steps: 2000
  save_total_limit: 2

data:
  max_train_samples: null
  max_validation_samples: 1024

runtime:
  mock: false
